In [1]:
import hd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import importlib

In [8]:
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)

In [25]:
# exponent vectors for the series of prime numbers
vecs = np.array([
    [1., 0., 0.],  # 2/1
    [-1., 1., 0.], # 3/2
    [-2., 0., 1.], # 5/4
    [1., 1., -1.], # 6/5
    [2., -1., 0.], # 4/3
    [-1., 0., 0.]  # 1/2
])

In [26]:
# This gets us the signed exponents
exploded = hd.tenney.exploded_hd_graph(3, vecs)
sess.run(exploded)

array([[ 1.        ,  0.        ,  0.        ],
       [-1.        ,  1.5849625 ,  0.        ],
       [-2.        ,  0.        ,  2.32192809],
       [ 1.        ,  1.5849625 , -2.32192809],
       [ 2.        , -1.5849625 ,  0.        ],
       [-1.        ,  0.        ,  0.        ]])

In [37]:
# Remove the column with the hd of the octave
octave_equivalence = exploded[:, 1:]
sess.run(octave_equivalence)

array([[ 0.        ,  0.        ],
       [ 1.5849625 ,  0.        ],
       [ 0.        ,  2.32192809],
       [ 1.5849625 , -2.32192809],
       [-1.5849625 ,  0.        ],
       [ 0.        ,  0.        ]])

In [40]:
# Any positive values should be "uphill" while negatives should be "downhill"
summed = tf.reduce_sum(octave_equivalence, axis=1)
sess.run(summed)

array([ 0.        ,  1.5849625 ,  2.32192809, -0.73696559, -1.5849625 ,
        0.        ])