In [1]:
import hd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import importlib

In [8]:
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)

In [25]:
# exponent vectors for the series of prime numbers
vecs = np.array([
    [1., 0., 0.],  # 2/1
    [-1., 1., 0.], # 3/2
    [-2., 0., 1.], # 5/4
    [1., 1., -1.], # 6/5
    [2., -1., 0.], # 4/3
    [-1., 0., 0.]  # 1/2
])

In [26]:
# This gets us the signed exponents
exploded = hd.tenney.exploded_hd_graph(3, vecs)
sess.run(exploded)

array([[ 1.        ,  0.        ,  0.        ],
       [-1.        ,  1.5849625 ,  0.        ],
       [-2.        ,  0.        ,  2.32192809],
       [ 1.        ,  1.5849625 , -2.32192809],
       [ 2.        , -1.5849625 ,  0.        ],
       [-1.        ,  0.        ,  0.        ]])

In [35]:
octave_equivalence = tf.pad(exploded[:, 1:], [[0, 0], [1, 0]])
sess.run(octave_equivalence)

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.5849625 ,  0.        ],
       [ 0.        ,  0.        ,  2.32192809],
       [ 0.        ,  1.5849625 , -2.32192809],
       [ 0.        , -1.5849625 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [28]:
# summed = tf.reduce_sum(exploded, axis=1)
sess.run(summed)

array([ 1.        ,  0.5849625 ,  0.32192809,  0.26303441,  0.4150375 ,
       -1.        ])